[package]
name = "openid-client-examples"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
open = "5.3.0"
openid-client = "0.2.6"
tokio = { version = "1.34.0", features = ["full"] }
